# Generated by Django 3.1 on 2020-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIdle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdata',
            name='semester_range',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='failed_last_semester',
            new_name='failed_a_semester',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='semester',
        ),
        migrations.AddField(
            model_name='userdata',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.CheckConstraint(check=models.Q(('hour__gte', 0), ('hour__lte', 23)), name='hour_range'),
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.CheckConstraint(check=models.Q(day__gte=0), name='day_range'),
        ),
    ]
